name: Normal Push Flow

on:
  push:
    branches: [ main ]
    tags-ignore: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
       
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test -c Release --verbosity normal

    - name: Build
      run: dotnet build -c Release --no-restore